services:
  postgres:
    image: postgres:15
    container_name: pool_postgres
    environment:
      POSTGRES_DB: pool_db
      POSTGRES_USER: pool_user
      POSTGRES_PASSWORD: pool_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pool_user -d pool_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  letta:
    image: letta/letta:latest
    container_name: pool_letta
    ports:
      - "8283:8283"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ~/.letta/.persist/pgdata:/var/lib/postgresql/data
    depends_on:
      - postgres

volumes:
  postgres_data: 