services:
  postgres:
    image: postgres:15
    container_name: pool_postgres
    environment:
      POSTGRES_DB: pool_db
      POSTGRES_USER: pool_user
      POSTGRES_PASSWORD: pool_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pool_user -d pool_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 